name: Build Android APK Simple

on:
  # Temporarily disabled - uncomment when Android development is ready
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'android/**'
  #     - '.github/workflows/build-android-simple.yml'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'android/**'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

# Run Android builds independently from web deployment
concurrency:
  group: "android-build-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    # Continue web deployment even if Android build fails
    continue-on-error: true
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Create Android SDK local.properties
      working-directory: ./android/android
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties

    - name: Make gradlew executable
      working-directory: ./android/android
      run: chmod +x gradlew

    - name: Build debug APK
      if: github.event.inputs.release_type == 'debug' || github.event.inputs.release_type == ''
      working-directory: ./android/android
      run: ./gradlew assembleDebug

    - name: Build release APK
      if: github.event.inputs.release_type == 'release' || github.ref == 'refs/heads/main'
      working-directory: ./android/android
      run: ./gradlew assembleRelease

    - name: Upload debug APK artifact
      if: github.event.inputs.release_type == 'debug' || github.event.inputs.release_type == ''
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/android/app/build/outputs/apk/debug/app-debug.apk

    - name: Upload release APK artifact
      if: github.event.inputs.release_type == 'release' || github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/android/app/build/outputs/apk/release/app-release.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: android-v${{ github.run_number }}
        name: Android App v${{ github.run_number }}
        body: |
          ## Abstract Algorithms Android App
          
          This is an automated release of the Abstract Algorithms blog as an Android app.
          
          ### Features:
          - 📱 Native Android WebView wrapper
          - 🔄 Offline caching support
          - 🎨 Optimized mobile interface
          - ⚡ Fast loading and navigation
          - 🔗 Deep linking support
          
          ### Installation:
          Download the APK file and install it on your Android device.
          Make sure to enable "Install from unknown sources" in your device settings.
          
          ### Changes:
          - Latest blog content from abstractalgorithms.github.io
          - Performance improvements
          - Bug fixes and stability improvements
        files: |
          android/android/app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
