name: Validate MDX Files

on:
  pull_request:
    paths:
      - 'src/posts/**/*.mdx'
  push:
    branches: [main, master]
    paths:
      - 'src/posts/**/*.mdx'

jobs:
  validate-mdx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate MDX files
      run: npm run validate:mdx
      
    - name: Test build
      run: npm run build
      
    - name: Comment on PR if validation fails
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ MDX validation failed! Please check the build logs and refer to `.copilot-instructions.md` for guidelines.'
          })
